/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import Metodes.MetodesIncidencia;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author alumne
 */
public class FrameIncidenciaModificar extends javax.swing.JFrame {

    /**
     * Creates new form FrameAtraccionsInserir
     */
    private String id;
    private String titol;
    private String descripcio;
    private String id_prioritat;
    private String id_estat;
    private ResultSet empleats = MetodesIncidencia.FillComboBox("select id,nom,cognom1,email from users where id_rol!=1 and id_rol!=2");

    public FrameIncidenciaModificar() {
        initComponents();
        carregarGUI();
    }

    public FrameIncidenciaModificar(String id, String titol, String descripcio, String id_prioritat, String id_estat) {

        initComponents();
        carregarGUI();

        this.id = id;
        this.titol = titol;
        this.descripcio = descripcio;
        this.id_prioritat = id_prioritat;
        this.id_estat = id_estat;

        incidentName.setText(titol);
        descField.setText(descripcio);
                
        try{
            while (empleats.next()){
                //Rellenamos elcombobox
                EmpleatsCB.addItem(empleats.getNString("nom") + " " + empleats.getNString("cognom1") + " - " + empleats.getNString("email"));
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Error: " + e);
        }
        prioritatCombo.setSelectedItem(id_prioritat);
        estatCombo.setSelectedItem(id_estat);
    }
    
    public FrameIncidenciaModificar(String id, String titol, String descripcio, String id_prioritat, String id_estat, String usuari_assignat) {

        initComponents();
        carregarGUI();

        this.id = id;
        this.titol = titol;
        this.descripcio = descripcio;
        this.id_prioritat = id_prioritat;
        this.id_estat = id_estat;

        incidentName.setText(titol);
        descField.setText(descripcio);

        try{
            while (empleats.next()){
                //Rellenamos elcombobox
                EmpleatsCB.addItem(empleats.getNString("nom") + " " + empleats.getNString("cognom1") + " - " + empleats.getNString("email"));
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Error: " + e);
        }
        prioritatCombo.setSelectedItem(id_prioritat);
        estatCombo.setSelectedItem(id_estat);
        EmpleatsCB.setSelectedItem(usuari_assignat);

    }

    private void carregarGUI() {
        this.setSize(500, 400);
        JScrollPane pane = new JScrollPane(this.getContentPane());
        this.setContentPane(pane);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        incidentName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descField = new javax.swing.JTextArea();
        backBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        prioritatCombo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        estatCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        EmpleatsCB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Univeylandia Parc - Incidencies - Modificar");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel1.setText("Incidències - Modificar");

        jLabel2.setText("Títol");

        jLabel9.setText("Descripció");

        descField.setColumns(20);
        descField.setRows(5);
        jScrollPane1.setViewportView(descField);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancel_small.png"))); // NOI18N
        backBtn.setText("Enrere");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        submitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ok_small.png"))); // NOI18N
        submitBtn.setText("Acceptar");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        jLabel10.setText("Prioritat");

        prioritatCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Urgent", "Normal", "Baixa" }));

        jLabel11.setText("Estat");

        estatCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "To-do", "In progress", "Done" }));

        jLabel3.setText("Empleat assignat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(incidentName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submitBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backBtn))
                    .addComponent(jScrollPane1)
                    .addComponent(prioritatCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estatCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmpleatsCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel3))
                        .addGap(0, 120, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(incidentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prioritatCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estatCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmpleatsCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(submitBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        FrameIncidenciaInicial fai = new FrameIncidenciaInicial();
        this.setVisible(false);
        fai.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(this.id);
            String titol = incidentName.getText();
            String descripcio = descField.getText();
            String prioritat = prioritatCombo.getSelectedItem().toString();
            String estat = estatCombo.getSelectedItem().toString();

            if (titol.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Introdueix dades per a poder modificar l'incidencia", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }

            if (descripcio.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Introdueix dades per a poder modificar l'incidencia", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }

            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Estas segur que vols modificar l'incidència", "Confirma per a modificar", dialogButton);
            if (dialogResult == 0) {
                int i = 0;
                
                int id_empleat_assignat = MetodesIncidencia.findID(EmpleatsCB.getSelectedItem().toString());
                
                if (prioritat == "Urgent") {
                    if (estat == "To-do") {
                        int priority = 3;
                        int state = 1;
                        
                        MetodesIncidencia.updateIncidentDades(id, titol, descripcio, state, priority, id_empleat_assignat);
                    }
                    else if (estat == "In progress") {
                        int priority = 3;
                        int state = 2;

                        MetodesIncidencia.updateIncidentDades(id, titol, descripcio, state, priority, id_empleat_assignat);

                    }
                    else if (estat == "Done") {
                        int priority = 3;
                        int state = 3;

                        MetodesIncidencia.updateIncidentDades(id, titol, descripcio, state, priority, id_empleat_assignat);
                    }
                }

                else if (prioritat == "Normal") {
                    if (estat == "To-do") {
                        int priority = 2;
                        int state = 1;

                        MetodesIncidencia.updateIncidentDades(id, titol, descripcio, state, priority, id_empleat_assignat);
                    }
                    else if (estat == "In progress") {
                        int priority = 2;
                        int state = 2;

                        MetodesIncidencia.updateIncidentDades(id, titol, descripcio, state, priority, id_empleat_assignat);
                    }
                    else if (estat == "Done") {
                        int priority = 2;
                        int state = 3;

                        MetodesIncidencia.updateIncidentDades(id, titol, descripcio, state, priority, id_empleat_assignat);
                    }

                }
                else if (prioritat == "Baixa") {
                    if (estat == "To-do") {
                        int priority = 1;
                        int state = 1;

                        MetodesIncidencia.updateIncidentDades(id, titol, descripcio, state, priority, id_empleat_assignat);
                    }
                    else if (estat == "In progress") {
                        int priority = 1;
                        int state = 2;

                        MetodesIncidencia.updateIncidentDades(id, titol, descripcio, state, priority, id_empleat_assignat);
                    }
                    else if (estat == "Done") {
                        int priority = 1;
                        int state = 3;

                        MetodesIncidencia.updateIncidentDades(id, titol, descripcio, state, priority, id_empleat_assignat);   
                    }
                }
            
            FrameIncidenciaInicial fai = new FrameIncidenciaInicial();
            this.setVisible(false);
            fai.setVisible(true);
            this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Incidència no modificada", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error: " + e);
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameIncidenciaModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameIncidenciaModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameIncidenciaModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameIncidenciaModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new FrameIncidenciaModificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> EmpleatsCB;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextArea descField;
    private javax.swing.JComboBox<String> estatCombo;
    private javax.swing.JTextField incidentName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> prioritatCombo;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
