/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classes.Incidencia;
import Metodes.MetodesIncidencia;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author alumne
 */
public class FrameIncidenciaInserir extends javax.swing.JFrame {

    /**
     * Creates new form FrameAtraccionsInserir
     */
    public FrameIncidenciaInserir() {
        initComponents();
        carregarGUI();
    }

    private void carregarGUI() {
        this.setSize(450, 350);
        JScrollPane pane = new JScrollPane(this.getContentPane());
        this.setContentPane(pane);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        titolIncidencia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descField = new javax.swing.JTextArea();
        backBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        prioritatCombo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        estatCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Univeylandia Parc - Atraccions");

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel1.setText("Incidències - Crear");

        jLabel2.setText("Títol");

        jLabel9.setText("Descripció");

        descField.setColumns(20);
        descField.setLineWrap(true);
        descField.setRows(5);
        jScrollPane1.setViewportView(descField);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancel_small.png"))); // NOI18N
        backBtn.setText("Enrere");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        submitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ok_small.png"))); // NOI18N
        submitBtn.setText("Acceptar");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        jLabel10.setText("Prioritat");

        prioritatCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Urgent", "Normal", "Baixa" }));

        jLabel11.setText("Estat");

        estatCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "To-do", "In progress", "Done" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                    .addComponent(titolIncidencia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(prioritatCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estatCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submitBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titolIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prioritatCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estatCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(submitBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        FrameIncidenciaInicial fai = new FrameIncidenciaInicial();
        this.setVisible(false);
        fai.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        try {

            String titol = titolIncidencia.getText();
            String descripcio = descField.getText();
            String prioritat = prioritatCombo.getSelectedItem().toString();
            String estat = estatCombo.getSelectedItem().toString();

            if (titol.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Introdueix dades per a poder modificar l'incidencia", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }

            if (descripcio.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Introdueix dades per a poder modificar l'incidencia", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }

            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Estas segur que vols introduir l'incidència", "Confirma per a inserir l'incidència", dialogButton);
            if (dialogResult == 0) {

                if (prioritat == "Urgent") {
                    int idUsuari = 1;

                    if (estat == "To-do") {
                        int priority = 3;
                        int state = 1;

                        Incidencia insertIncident = new Incidencia(titol, descripcio, state, priority);
                        MetodesIncidencia.registerIncident(insertIncident);
                        JOptionPane.showMessageDialog(null, "Incidència creada correctament");

                        FrameIncidenciaInicial fai = new FrameIncidenciaInicial();
                        this.setVisible(false);
                        fai.setVisible(true);
                        this.dispose();

                    }
                    if (estat == "In progress") {
                        int priority = 3;
                        int state = 2;

                        Incidencia insertIncident = new Incidencia(titol, descripcio, state, priority);
                        MetodesIncidencia.registerIncident(insertIncident);
                        JOptionPane.showMessageDialog(null, "Incidència creada correctament");

                        FrameIncidenciaInicial fai = new FrameIncidenciaInicial();
                        this.setVisible(false);
                        fai.setVisible(true);
                        this.dispose();

                    }
                    if (estat == "Done") {
                        int priority = 3;
                        int state = 3;

                        Incidencia insertIncident = new Incidencia(titol, descripcio, state, priority);
                        MetodesIncidencia.registerIncident(insertIncident);
                        JOptionPane.showMessageDialog(null, "Incidència creada correctament");
                    }
                }

                if (prioritat == "Normal") {
                    if (estat == "To-do") {
                        int priority = 2;
                        int state = 1;

                        Incidencia insertIncident = new Incidencia(titol, descripcio, state, priority);
                        MetodesIncidencia.registerIncident(insertIncident);
                        JOptionPane.showMessageDialog(null, "Incidència creada correctament");

                        FrameIncidenciaInicial fai = new FrameIncidenciaInicial();
                        this.setVisible(false);
                        fai.setVisible(true);
                        this.dispose();
                    }
                    if (estat == "In progress") {
                        int priority = 2;
                        int state = 2;

                        Incidencia insertIncident = new Incidencia(titol, descripcio, state, priority);
                        MetodesIncidencia.registerIncident(insertIncident);
                        JOptionPane.showMessageDialog(null, "Incidència creada correctament");

                        FrameIncidenciaInicial fai = new FrameIncidenciaInicial();
                        this.setVisible(false);
                        fai.setVisible(true);
                        this.dispose();

                    }
                    if (estat == "Done") {
                        int priority = 2;
                        int state = 3;

                        Incidencia insertIncident = new Incidencia(titol, descripcio, state, priority);
                        MetodesIncidencia.registerIncident(insertIncident);
                        JOptionPane.showMessageDialog(null, "Incidència creada correctament");

                        FrameIncidenciaInicial fai = new FrameIncidenciaInicial();
                        this.setVisible(false);
                        fai.setVisible(true);
                        this.dispose();

                    }

                }
                if (prioritat == "Baixa") {
                    if (estat == "To-do") {
                        int priority = 1;
                        int state = 1;

                        Incidencia insertIncident = new Incidencia(titol, descripcio, state, priority);
                        MetodesIncidencia.registerIncident(insertIncident);
                        JOptionPane.showMessageDialog(null, "Incidència creada correctament");;

                        FrameIncidenciaInicial fai = new FrameIncidenciaInicial();
                        this.setVisible(false);
                        fai.setVisible(true);
                        this.dispose();

                    }
                    if (estat == "In progress") {
                        int priority = 1;
                        int state = 2;

                        Incidencia insertIncident = new Incidencia(titol, descripcio, state, priority);
                        MetodesIncidencia.registerIncident(insertIncident);
                        JOptionPane.showMessageDialog(null, "Incidència creada correctament");

                        FrameIncidenciaInicial fai = new FrameIncidenciaInicial();
                        this.setVisible(false);
                        fai.setVisible(true);
                        this.dispose();
                    }
                    if (estat == "Done") {
                        int priority = 1;
                        int state = 3;

                        Incidencia insertIncident = new Incidencia(titol, descripcio, state, priority);
                        MetodesIncidencia.registerIncident(insertIncident);
                        JOptionPane.showMessageDialog(null, "Incidència creada correctament");

                        FrameIncidenciaInicial fai = new FrameIncidenciaInicial();
                        this.setVisible(false);
                        fai.setVisible(true);
                        this.dispose();
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Incidència no modificada", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {

        }        // TODO add your handling code here:
    }//GEN-LAST:event_submitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameIncidenciaInserir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameIncidenciaInserir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameIncidenciaInserir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameIncidenciaInserir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameIncidenciaInserir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextArea descField;
    private javax.swing.JComboBox<String> estatCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> prioritatCombo;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField titolIncidencia;
    // End of variables declaration//GEN-END:variables
}
