package Frames;

import Auxiliar.MetodesGenerals;
import Auxiliar.SharedData;
import Classes.Client;
import Classes.Ticket;
import Metodes.MetodesClient;
import Metodes.MetodesTicket;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 *
 * @author GRUP2: Ferran Climent
 */
public class FrameTicketsMostrar extends javax.swing.JFrame {
    
    
    String id_ticket;
    Statement statement = null;
    ResultSet resultSet = null;
    ResultSet resultTipus = null;

    /**
     * Creates new form FrameAtraccionsInserir
     */
    public FrameTicketsMostrar() {
        initComponents();
        carregarGUI();
        dataCompra.setDateFormatString(MetodesGenerals.DATE_FORMAT);
    }
    
    private void carregarGUI() {
        this.setSize(450, 350);
        JScrollPane pane = new JScrollPane(this.getContentPane());
        this.setContentPane(pane);
        this.setLocationRelativeTo(null);
        FrameTicketsModificar();
    }
    
     /**
     * Metode per a cargar les variables del objecte de tipus Ticket.
     *
     */
    public void FrameTicketsModificar() {
        String idTicket = SharedData.getIdTicket();

        Ticket tck = MetodesTicket.getDadesTicket(idTicket,Ticket.getQueryShow());
        
        //System.out.println(tck.toString());
        DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        Date dataCompraT = null;
        try {
            //System.out.println(tck.getData_compra());
            dataCompraT = format.parse(tck.getData_compra());
        } catch (Exception ex) {
            Logger.getLogger(FrameAtraccionsMostrar.class.getName()).log(Level.SEVERE, null, ex);
        }
        NomComprador.setText(tck.getComprador());
        selectTipus.setText(tck.getTipus_ticket_string());
        numViatges.setValue(tck.getTickets_viatges());
        preu.setValue(tck.getPreu());
        selectEstat.setSelectedItem(tck.getEstat());
        dataCompra.setDate(dataCompraT);
        
        NomComprador.setEnabled(false);
        selectTipus.setEnabled(false);
        numViatges.setEnabled(false);
        preu.setEnabled(false);
        selectEstat.setEnabled(false);
        dataCompra.setEnabled(false);
        
        //this.setExtendedState(this.MAXIMIZED_BOTH);
        /*loadcombo();
        id_ticket = SharedData.getIdTicket();
        String dades_ticket_sql = "SELECT  p.id,u.nom as Nom,u.cognom1 as Cognom, tp.id as id_tipus, tp.nom as tipus_tiquet, vp.created_at as data_compra, ap.tickets_viatges, ap.preu, p.estat FROM users u,venta_productes vp, productes p left join atributs_producte ap on p.atributs = ap.id left join tipus_producte tp on ap.nom = tp.id WHERE p.id = " + id_ticket;
        System.out.println("id_seleccionat update: " + id_ticket);
        System.out.println(dades_ticket_sql);
        try {
            statement = Auxiliar.DBConnection.getConnection().createStatement();
            resultSet = statement.executeQuery(dades_ticket_sql);
            resultSet.first();
            selectTipus.setSelectedItem(resultSet.getString("id_tipus" + "tipus_tiquet"));
            preu.setValue(resultSet.getInt("preu"));
            numViatges.setValue(resultSet.getInt("tickets_viatges"));
            
            DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            Date dateInaug = null;
            try {
                dateInaug = format.parse(resultSet.getString("data_compra"));
            } catch (ParseException ex) {
                Logger.getLogger(FrameTicketsMostrar.class.getName()).log(Level.SEVERE, null, ex);
            }
        
            dataCompra.setDate(dateInaug);

            if (resultSet.getBoolean("estat")) {
                selectEstat.setSelectedItem("Actiu");
            } else {
                selectEstat.setSelectedItem("Desactivat");
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, e);
        } /*finally {
            try {
                statement.close();
                Auxiliar.DBConnection.disconnect();
            } catch (SQLException e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(this, e);
            }
        }*/
        
        
                

    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dataCompra = new com.toedter.calendar.JDateChooser();
        backBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        selectEstat = new javax.swing.JComboBox<>();
        numViatges = new javax.swing.JSpinner();
        preu = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        NomComprador = new javax.swing.JTextField();
        selectTipus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Univeylandia Parc - Client - Modificar");

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel1.setText("Tickets - Mostrar");

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancel_small.png"))); // NOI18N
        backBtn.setText("Enrere");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Data compra");

        jLabel2.setText("Número de viatges");

        jLabel3.setText("Tipus");

        jLabel4.setText("Preu (€)");

        jLabel5.setText("Estat");

        selectEstat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Actiu", "Desactivat"}));

        jLabel7.setText("Comprador");

        selectTipus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTipusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(282, Short.MAX_VALUE)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(NomComprador))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(numViatges))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(preu))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(selectEstat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dataCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(selectTipus)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectTipus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numViatges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(preu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectEstat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        FrameTicketsInicial fai = new FrameTicketsInicial();
        this.setVisible(false);
        fai.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void selectTipusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTipusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectTipusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTicketsMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTicketsMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTicketsMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTicketsMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTicketsMostrar().setVisible(true);
            }
        });
    }
    /*void loadcombo() {
        try {
            statement = Auxiliar.DBConnection.getConnection().createStatement();
            resultTipus = statement.executeQuery("select nom from tipus_producte where id in (1,2,3,4,5,6,7);");
            while (resultTipus.next()) {
                selectTipus.addItem(resultTipus.getString(1));
            }
            Auxiliar.DBConnection.disconnect();
        } catch (Exception e) {
            System.out.println("Error" + e);
        }
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NomComprador;
    private javax.swing.JButton backBtn;
    private com.toedter.calendar.JDateChooser dataCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSpinner numViatges;
    private javax.swing.JSpinner preu;
    private javax.swing.JComboBox<String> selectEstat;
    private javax.swing.JTextField selectTipus;
    // End of variables declaration//GEN-END:variables
}
